/**
 * Códigos públicos e estáveis do contrato HTTP.
 *
 * Mensagens podem evoluir; integrações e interfaces devem tomar decisões
 * apenas com base nestes códigos e no status HTTP.
 */
export const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_JSON: 'INVALID_JSON',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  REQUEST_ERROR: 'REQUEST_ERROR',
  AUTH_INVITE_NOT_FOUND: 'AUTH_INVITE_NOT_FOUND',
  AUTH_CODE_RATE_LIMITED: 'AUTH_CODE_RATE_LIMITED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_ACTIVATION_CODE: 'AUTH_INVALID_ACTIVATION_CODE',
  AUTH_INVALID_ACTIVATION_TOKEN: 'AUTH_INVALID_ACTIVATION_TOKEN',
  AUTH_PASSWORD_ALREADY_SET: 'AUTH_PASSWORD_ALREADY_SET',
  AUTH_USER_INACTIVE: 'AUTH_USER_INACTIVE',
  AUTH_INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  EMAIL_UNAVAILABLE: 'EMAIL_UNAVAILABLE',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});
