const MILLISECONDS_PER_MINUTE = 60_000;
const ACTIVATION_CODE_EXPIRATION_MINUTES = 10;

export const JWT_EXPIRATION = Object.freeze({
  ACCESS_TOKEN: '15m',
  REFRESH_TOKEN: '7d',
  PASSWORD_ACTIVATION_TOKEN: '10m',
});

export const PASSWORD_ACTIVATION = Object.freeze({
  CODE_LENGTH: 6,
  CODE_MIN_VALUE: 100_000,
  CODE_MAX_VALUE_EXCLUSIVE: 1_000_000,
  CODE_HASH_ROUNDS: 10,
  MAX_ATTEMPTS: 5,
  ATTEMPT_INCREMENT: 1,
  EXPECTED_UPDATE_COUNT: 1,
  RESEND_COOLDOWN_MS: MILLISECONDS_PER_MINUTE,
  EXPIRATION_MINUTES: ACTIVATION_CODE_EXPIRATION_MINUTES,
  EXPIRATION_MS: ACTIVATION_CODE_EXPIRATION_MINUTES * MILLISECONDS_PER_MINUTE,
});

export const PASSWORD_POLICY = Object.freeze({
  MIN_LENGTH: 8,
  HASH_ROUNDS: 12,
});

export const JWT_SECRET_MIN_LENGTH = 32;
